import type { ThemeConfig } from "antd";

const color = {
  primary: "#2B42E5",
  primaryHover: "#2338C2",
  primaryActive: "#182CC2",
  primarySubtle: "#EBF2FD",
  accent: "#FBAE40",
  textPrimary: "#292929",
  textSecondary: "#4B4B4C",
  textMuted: "#5F6670",
  textDisabled: "#A3A9B1",
  textInverse: "#FFFFFF",
  textInverseMuted: "#9BA8F9",
  surfacePage: "#F5F6F8",
  surfacePanel: "#FFFFFF",
  surfaceMuted: "#EEEEEE",
  surfaceInverse: "#081240",
  borderSubtle: "#DDE1E6",
  borderControl: "#7D8590",
  overlayScrim: "#08124073",
  success: "#197A4A",
  successBg: "#E6F4EC",
  warning: "#A85800",
  warningBg: "#FFF4DF",
  danger: "#C62832",
  dangerHover: "#B3202A",
  dangerBg: "#FDECEC",
  info: "#1B64C8",
  infoBg: "#EBF2FD",
} as const;

/** Design tokens antd has no counterpart for: the accent colour, the focus ring offset and the ease-in curve. antd publishes every token key as a `--ant-*` CSS variable, which the stylesheet reads. */
const customToken = {
  colorAccent: color.accent,
  focusRingOffset: 2,
  motionEaseIn: "cubic-bezier(0.55, 0.055, 0.675, 0.19)",
};

const fontFamily = "PT Sans, Segoe UI, Roboto, Arial, sans-serif";
const fontFamilyCode = "PT Mono, Consolas, Courier New, monospace";

const isMotionReduced =
  window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false;

/** antd theme derived from the design tokens; every antd text and primary-border token is set explicitly. */
export const theme: ThemeConfig = {
  token: {
    colorPrimary: color.primary,
    colorPrimaryHover: color.primaryHover,
    colorPrimaryActive: color.primaryActive,
    colorPrimaryBg: color.primarySubtle,
    colorPrimaryBorder: color.primary,
    colorLink: color.primary,
    colorLinkHover: color.primaryHover,
    colorLinkActive: color.primaryActive,
    colorTextBase: color.textPrimary,
    colorText: color.textPrimary,
    colorTextSecondary: color.textSecondary,
    colorTextTertiary: color.textMuted,
    colorTextPlaceholder: color.textMuted,
    colorTextQuaternary: color.textDisabled,
    colorTextDisabled: color.textDisabled,
    colorTextLightSolid: color.textInverse,
    colorBgLayout: color.surfacePage,
    colorBgContainer: color.surfacePanel,
    colorBgElevated: color.surfacePanel,
    colorFillTertiary: color.surfaceMuted,
    colorBgContainerDisabled: color.surfaceMuted,
    colorBgMask: color.overlayScrim,
    colorBgSpotlight: color.surfaceInverse,
    colorBorder: color.borderControl,
    colorBorderSecondary: color.borderSubtle,
    colorSplit: color.borderSubtle,
    colorSuccess: color.success,
    colorSuccessBg: color.successBg,
    colorWarning: color.warning,
    colorWarningBg: color.warningBg,
    colorError: color.danger,
    colorErrorBg: color.dangerBg,
    colorErrorHover: color.dangerHover,
    colorErrorActive: color.dangerHover,
    colorInfo: color.info,
    colorInfoBg: color.infoBg,

    fontFamily,
    fontFamilyCode,
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 30,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    lineHeight: 1.5714,
    lineHeightLG: 1.5,
    lineHeightSM: 1.6667,
    lineHeightHeading1: 1.2667,
    lineHeightHeading2: 1.3333,
    lineHeightHeading3: 1.4,
    lineHeightHeading4: 1.5,
    lineHeightHeading5: 1.5714,
    fontWeightStrong: 700,

    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 48,
    controlHeightSM: 24,
    controlHeight: 32,
    controlHeightLG: 40,

    borderRadius: 4,
    borderRadiusSM: 2,
    borderRadiusXS: 2,
    borderRadiusLG: 8,
    lineWidth: 1,
    lineWidthFocus: 2,
    controlOutlineWidth: 2,
    ...customToken,

    boxShadow: "0 8px 24px rgba(8, 18, 64, 0.16)",
    boxShadowSecondary: "0 4px 12px rgba(8, 18, 64, 0.12)",
    boxShadowTertiary: "0 1px 2px rgba(8, 18, 64, 0.08)",

    motion: !isMotionReduced,
    motionEaseOut: "cubic-bezier(0.215, 0.61, 0.355, 1)",
    motionEaseInOut: "cubic-bezier(0.645, 0.045, 0.355, 1)",
  },
  components: {
    Layout: {
      headerBg: color.surfaceInverse,
      headerColor: color.textInverse,
      headerHeight: 56,
      headerPadding: "0 24px",
      siderBg: color.surfaceInverse,
    },
    Menu: {
      darkItemBg: color.surfaceInverse,
      darkItemColor: color.textInverseMuted,
    },
    Button: {
      fontWeight: 700,
      defaultShadow: "none",
      primaryShadow: "none",
      dangerShadow: "none",
      defaultHoverBg: color.primarySubtle,
      defaultActiveBg: color.primarySubtle,
      defaultHoverColor: color.primary,
      defaultActiveColor: color.primaryActive,
      defaultHoverBorderColor: color.primary,
    },
    Table: {
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      headerBg: color.surfaceMuted,
      headerColor: color.textSecondary,
      rowHoverBg: color.surfacePage,
      rowSelectedBg: color.primarySubtle,
      rowSelectedHoverBg: color.primarySubtle,
      borderColor: color.borderSubtle,
    },
    Form: {
      itemMarginBottom: 24,
      verticalLabelPadding: "0 0 8px",
    },
    Card: {
      bodyPadding: 24,
      bodyPaddingSM: 12,
      headerPadding: 24,
    },
    Tabs: {
      itemColor: color.textSecondary,
      itemHoverColor: color.textPrimary,
      itemSelectedColor: color.primary,
      inkBarColor: color.primary,
    },
    Modal: {
      titleFontSize: 24,
      titleLineHeight: 1.3333,
    },
    Alert: {
      defaultPadding: "12px",
    },
  },
};
